apiVersion: apps/v1
kind: Deployment # change here
metadata:
  name: react-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-page
  template:
    metadata:
      labels:
        app: react-page
    spec:
      containers:
      - image: lehuuan18/react-test:latest
        name: react-page
        ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: react-page
spec:
  type: NodePort
  selector:
    app: react-page
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000