---
plugin: aws_ec2
regions:
  - ap-southeast-1
aws_access_key: AKIARP6QI3THRS6QU6X5
aws_secret_key: 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
keyed_groups:
  - prefix: tag
    key: tags
include_filters:
  - tag:Name:
    - 'Worker'
compose:
  ansible_host: public_ip_address
