---
plugin: aws_ec2
regions:
  - ap-southeast-1
aws_access_key: this_is_fake
aws_secret_key: this_is_fake
keyed_groups:
  - prefix: tag
    key: tags
include_filters:
  - tag:Name:
    - 'Worker'
compose:
  ansible_host: public_ip_address
