---
plugin: aws_ec2
regions:
  - ap-southeast-1
aws_access_key: ${{ secrets.aws_access_key }}
aws_secret_key: ${{ secrets.aws_secret_key }}
keyed_groups:
  - prefix: tag
    key: tags
include_filters:
  - tag:Name:
    - 'Worker'
compose:
  ansible_host: public_ip_address
