version: 2.1
orbs:
  node: circleci/node@5.0.2
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
  
  deploy:
    executor: python/default
    steps:
      - run: 
          command: |
            echo $aws_access_key
            echo $aws_secret_key
          name: deploy ansible


workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test

