version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - run:
          command: ls
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  
  deploy:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: ls


workflows:
  test_my_app:
    jobs:
      - build_and_test

