version: 2.1
orbs:
  node: circleci/node@5.0.2
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - run:
          command: |
            cd ansible
            cat ./inventory/inventory_aws_ec2.yml

workflows:
  test_app:
    jobs:
      - build_and_test

            

