version: 2.1
orbs:
  node: circleci/node@5.0.2
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - run:
          command: |
            pwd
            cd ..
            ls
  
  deploy:
    executor: python/default
    steps:
      - run: 
          command: |
            echo aws_access_key_ansible = "$aws_access_key" >> "${BASH_ENV}"
            echo aws_secret_key_ansible = "$aws_secret_key" >> "${BASH_ENV}"
            echo $aws_access_key_ansible
            echo $aws_secret_key_ansible
          name: deploy ansible

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy

