version: 2.1
orbs:
  node: circleci/node@5.0.2
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install python3-pip -y
            sudo pip3 install boto3
            sudo apt-get install ansible
            pip install ansible
          name: install ansible and aws cli
      - run:
          command: |
            cd ansible
            sed -i '5s/this_is_fake/"$(aws_access_key)"' ./inventory/inventory_aws_ec2.yml
            sed -i '6s/this_is_fake/"$(aws_secret_key)"' ./inventory/inventory_aws_ec2.yml
            ansible-inventory --graph


workflows:
  test_app:
    jobs:
      - build_and_test

            

