version: 2.1
orbs:
  node: circleci/node@5.0.2
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - run:
          command: ls
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  
  deploy:
    executor: python/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            cd ansible
            ls
            python3 --version
            sudo apt-get install python-boto3


workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test

