version: 2.1
orbs:
  node: circleci/node@5.0.2
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: aws_access_key
          aws-secret-access-key: aws_secret_key
          aws-region: aws_region_name
      - run: |
          commit_hash=`git rev-parse HEAD`
          aws deploy create-deployment \
            --application-name CodeDeployGitHubDemo-App \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name CodeDeployGitHubDemo-DepGrp \
            --description "My GitHub deployment demo" \
            --github-location repository=anle20/react-landing-page-template-2021,commitId=$commit_hash

workflows:
  test_app:
    jobs:
      - deploy

